version: '0.2.0.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
  PATH: "%PYTHON%;%PYTHON%\\scripts;%PATH%"

install:
  # We need wheel installed to build wheels
  - pip install wheel
  - pip install -r requirements_travis.txt
  - pip install pypiwin32     # XXX: workaround to twisted dependancy bug
  - python setup.py sdist bdist_wheel
  - pip install .

build: off

test_script:
  - pytest -s --verbose --cov=dnsagent dnsagent/tests/

on_success:
  - cmd < benchmark.sh

artifacts:
  - path: 'dist\*.tar.gz'
  - path: 'dist\*.whl'
