environment:
  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
  PATH: "%PYTHON%;%PYTHON%\\scripts;%PATH%"

install:
  # We need wheel installed to build wheels
  - pip install wheel
  - pip install -r requirements_travis.txt
  - pip install pypiwin32     # workaround to twisted dependancy bug
  - pip install .

build: off

test_script:
  # Put your test command here.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python evrsion you want to use on PATH.
  - pytest -s --verbose --cov=dnsagent dnsagent/tests/

on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
  - cmd < benchmark.sh
