language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# command to install dependencies
install:
  - pip install -r requirements_travis.txt
  - python setup.py install --record record.txt

# command to run tests
script:
  pytest -s --verbose --cov=dnsagent dnsagent/tests/
  && codecov
