language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# command to install dependencies
install:
  - pip install -r requirements_travis.txt
  - pip install .

# command to run tests
script:
  - pytest -s --verbose --cov=dnsagent dnsagent/tests/
  - codecov

after_success:
  - python -m dnsagent.scripts.benchmark --process 1
  - python -m dnsagent.scripts.benchmark --process 2
  - python -m dnsagent.scripts.benchmark --process 3
  - python -m dnsagent.scripts.benchmark --process 2 --tcp-only
  - python -m dnsagent.scripts.benchmark --process 2 --tcp-only
    --no-reuse-resolver --concurrency 50 --count 2000
  - python -m dnsagent.scripts.benchmark --process 2 --tcp-only
    --no-reuse-resolver --concurrency 100 --count 2000
